### ISSUE TITLE
Karma does not update when rating is reset to 0

### ISSUE THREAD

**Issue by dschey82** [stephenmcd/drum#18] opened 2015-06-10 21:04 UTC
To reproduce:
Log in to an account.
Find a link submitted by a user other than this account.
Click the Upvote arrow several times.

Result:
Karma of the submitting user increments each time the rating is +1, does not decrement when clicking the arrow resets the link rating, meaning a single user can use a single link to control another user's karma.

Expected Result:
Karma decrements (or increments if using the down arrow) when an arrow click resets the user's rating of a link to 0.

**Comment by stephenmcd** [comment] 2015-06-10 23:55
I can't reproduce using the development branch - it's possibly already fixed in #17

Can you test against it?

**Comment by dschey82** [comment] 2015-06-11 17:13
Thank you. I'm unable to reproduce the issue after updating drum/links/models.py with the fix from #17.

**Comment by stephenmcd** [comment] 2015-06-12 00:52
Awesome! Thanks for checking. I'll try and push a new release soon.

**Closed by stephenmcd** 2015-06-12 00:52 UTC
